# Railway deployment configuration
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python web_ui/app.py"
healthcheckPath = "/platform-login"
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
PORT = "5000"
FLASK_ENV = "production"