# Railway deployment configuration
[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
PORT = "5000"
FLASK_ENV = "production"