#!/usr/bin/env python3
"""
Check what order_id fields exist in both orders and positions tables
Verify the relationship and what's actually stored
"""

import os
from dotenv import load_dotenv
from supabase import create_client
import json

# Load environment variables
load_dotenv()

# Initialize Supabase client
supabase_url = os.getenv('SUPABASE_URL')
supabase_key = os.getenv('SUPABASE_ANON_KEY')
supabase = create_client(supabase_url, supabase_key)

# The orphaned order ID
orphaned_order_id = '659e74cc-610f-4bb6-ab0c-6e5b7f09d1ee'

print("=" * 80)
print("CHECKING ORDER_ID FIELDS IN DATABASE")
print("=" * 80)

# 1. Check the orders table
print("\n📋 ORDERS TABLE - Checking orphaned order:")
order_result = supabase.table('orders').select('*').eq('id', orphaned_order_id).execute()

if order_result.data:
    order = order_result.data[0]
    print(f"  ✓ Found order in database")
    print(f"  - id (PRIMARY KEY): {order['id']}")
    print(f"  - order_id (field): {order.get('order_id', 'NULL')}")
    print(f"  - symbol: {order['symbol']}")
    print(f"  - order_type: {order['order_type']}")
    print(f"  - created_at: {order['created_at']}")
    
    # Check what order_id actually contains
    if order.get('order_id'):
        print(f"\n  📊 order_id field contains: {order['order_id']}")
        print(f"     (This is the internal UUID from VirtualOrder)")
    else:
        print(f"\n  ⚠️  order_id field is NULL/empty")

# 2. Check positions table schema and look for buy_order_id
print("\n" + "=" * 80)
print("📊 POSITIONS TABLE - Check for buy_order_id column:")

# Get a sample position to see schema
sample_positions = supabase.table('positions').select('*').limit(1).execute()

if sample_positions.data:
    position = sample_positions.data[0]
    print(f"  ✓ Sample position found")
    print(f"  - id (PRIMARY KEY): {position['id']}")
    
    # Check if buy_order_id exists
    if 'buy_order_id' in position:
        print(f"  - buy_order_id: {position.get('buy_order_id', 'NULL')}")
        print(f"    ✅ buy_order_id column EXISTS")
    else:
        print(f"  - buy_order_id: COLUMN DOES NOT EXIST")
        print(f"    ❌ This would explain the foreign key issue!")
    
    # Check if sell_order_id exists
    if 'sell_order_id' in position:
        print(f"  - sell_order_id: {position.get('sell_order_id', 'NULL')}")
        print(f"    ✅ sell_order_id column EXISTS")
    else:
        print(f"  - sell_order_id: COLUMN DOES NOT EXIST")
    
    print(f"\n  Full position fields:")
    for key in position.keys():
        if 'order' in key.lower():
            print(f"    - {key}: {position[key]}")

# 3. Check all positions to see buy_order_id usage
print("\n" + "=" * 80)
print("🔍 ANALYZING ALL POSITIONS - buy_order_id usage:")

all_positions = supabase.table('positions').select('id, symbol, buy_order_id, entry_time').eq('trading_mode', 'paper').limit(20).execute()

if all_positions.data:
    positions_with_buy_order_id = 0
    positions_without_buy_order_id = 0
    
    for pos in all_positions.data:
        if pos.get('buy_order_id'):
            positions_with_buy_order_id += 1
        else:
            positions_without_buy_order_id += 1
    
    print(f"  Total positions checked: {len(all_positions.data)}")
    print(f"  - With buy_order_id: {positions_with_buy_order_id}")
    print(f"  - Without buy_order_id: {positions_without_buy_order_id}")

# 4. Try to verify foreign key relationship
print("\n" + "=" * 80)
print("🔗 FOREIGN KEY RELATIONSHIP:")

if all_positions.data and all_positions.data[0].get('buy_order_id'):
    # Pick a position with buy_order_id
    sample_pos = all_positions.data[0]
    buy_order_id = sample_pos['buy_order_id']
    
    print(f"  Testing with position: {sample_pos['symbol']}")
    print(f"  Position's buy_order_id: {buy_order_id}")
    
    # Check if this ID exists in orders table
    linked_order = supabase.table('orders').select('*').eq('id', buy_order_id).execute()
    
    if linked_order.data:
        print(f"  ✅ VALID: buy_order_id references orders.id (PRIMARY KEY)")
        print(f"     Linked order: {linked_order.data[0]['symbol']} @ ₹{linked_order.data[0]['price']}")
    else:
        print(f"  ❌ BROKEN: buy_order_id does not exist in orders table!")

# 5. Summary and explanation
print("\n" + "=" * 80)
print("UNDERSTANDING THE RELATIONSHIP:")
print("=" * 80)

print("""
DATABASE SCHEMA:

1. ORDERS TABLE:
   - id (UUID, PRIMARY KEY) ← Generated by database
   - order_id (VARCHAR) ← Internal UUID from VirtualOrder object
   
2. POSITIONS TABLE:
   - id (UUID, PRIMARY KEY)
   - buy_order_id (UUID) ← Should reference orders.id (PRIMARY KEY)
   - sell_order_id (UUID) ← Should reference orders.id (PRIMARY KEY)

THE ISSUE:
----------
Code at line 632 tries to use: order.metadata.get('database_id')

This should contain the orders.id (PRIMARY KEY from database) that was
returned when the order was saved.

But the metadata['database_id'] is only stored in MEMORY, not persisted
to the database signal_data field.

When position creation reads order.metadata['database_id'], it's reading
from the IN-MEMORY order object, which should have this value IF the order
was just created in the same execution cycle.

HYPOTHESIS:
-----------
If order.metadata['database_id'] is None at line 632, it means:
1. The in-memory order object doesn't have this metadata
2. This could happen if there's a race condition or timing issue
3. The order was saved but metadata wasn't set before position creation

CORRECT APPROACH:
-----------------
Instead of relying on order.metadata['database_id'], the code should:
- Use the saved_order_id returned from save_order() directly
- Or query the database to get the order id
- Don't rely on in-memory metadata that might not be set
""")

print("=" * 80)
